name: Build and Run ASP.NET Razor EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Ensures it runs on a Windows machine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Ensures the latest code is pulled

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Change to your actual .NET version

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build the Application
        run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true

      - name: Debug:List All Files After Build
        run: Get-ChildItem -Path . -Recurse

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: MyRazorApp-EXE
          path: bin/Release/net6.0/win-x64/publish/MyRazorApp.exe
