name: Build and Run ASP.NET Razor EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Ensures the build runs on Windows

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Setup .NET
        uses: actions/setup-dotnet@v4  # Updated to latest version
        with:
          dotnet-version: '6.0.x'  # Change if using .NET 7 or 8

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build the Application
        run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true

      - name: List Published Files
        run: dir bin\Release\net6.0\win-x64\publish  # Debugging step to verify .exe exists

      - name: Upload Executable
        uses: actions/upload-artifact@v4  # Updated to latest version
        with:
          name: MyRazorApp-EXE
          path: bin/Release/net6.0/win-x64/publish/MyRazorApp.exe
